from django.urls import path
from .views import (
    TradeDeleteView,
    index,
    get_live_price,
    StrategyCreateView,
    StrategyEditView,
    StrategyListView,
    StrategyDeleteView,
    TradeCreateView,
    TradeEditView,
    TradeDetailView,
    TradeListView,
    StrategyDetailView,
    StrategyListView,
    StrategyDeleteView,
    execute_trading_script,
    get_recommended_trade,
    download_ticker_file,
    download_script,
    script_loading,
    live_view,
    search_stock,
    historical_chart,
    get_historical_price,
)

urlpatterns = [
    path('', index, name="index"),
    path('<str:stock>/graph/', live_view, name="stock-price"),
    path('<str:stock>/ajax-price/', get_live_price, name="price"),
    path('<str:stock>/<str:interval>/history-graph/', historical_chart, name="history-price"),
    path('<str:stock>/<str:interval>/ajax-historical-price/', get_historical_price, name="get-historical-prices"),
    path('strategy/', StrategyListView.as_view(), name="strategy-list"),
    path('strategy/<int:pk>/', StrategyDetailView.as_view(), name='strategy-detail'),
    path('strategy/<int:pk>/edit/', StrategyEditView.as_view(), name='strategy-edit'),
    path('strategy/<int:pk>/delete/', StrategyDeleteView.as_view(), name='strategy-delete'),
    path('strategy/new/', StrategyCreateView.as_view(), name ='strategy-create'),
    path('trade/', TradeListView.as_view(), name ='trade-list'),
    path('trade/new/', TradeCreateView.as_view(), name ='trade-create'),
    path('trade/<int:pk>/', TradeDetailView.as_view(), name='trade-detail'),
    path('trade/<int:pk>/edit/', TradeEditView.as_view(), name='trade-edit'),
    path('trade/<int:pk>/delete/', TradeDeleteView.as_view(), name='trade-delete'),
    path('trade/<int:pk>/execute/', execute_trading_script, name='execute-script'),
    path('trade/<int:pk>/excel/', get_recommended_trade, name='get-trade'),
    path('trade/<int:pk>/tickers/', download_ticker_file, name='download-ticker'),
    path('trade/<int:pk>/script/', download_script, name='download-script'),
    path('trade/<int:pk>/loading/', script_loading, name='loading'),
    path('search-stock/', search_stock, name='search-stock'),
]