# Generated by Django 3.0.8 on 2021-08-24 16:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210719_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
