# Generated by Django 3.0.8 on 2021-08-24 17:02

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stocks',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
