# Generated by Django 3.0.8 on 2021-08-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210824_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stocks',
            field=models.CharField(default='', max_length=500),
        ),
    ]
