# Generated by Django 3.0.8 on 2021-08-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210825_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='portfolio',
        ),
    ]
