# Generated by Django 3.0.8 on 2021-09-01 20:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
