# Generated by Django 3.0.8 on 2021-07-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('script', models.FileField(upload_to='strategy_scripts/')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickers', models.FileField(upload_to='input_files/')),
                ('portfolio_size', models.FloatField()),
                ('trading_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.Strategy')),
            ],
        ),
    ]
