# Generated by Django 3.0.8 on 2021-07-20 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='script',
            field=models.FileField(upload_to='strategy_scripts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py'])]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='tickers',
            field=models.FileField(upload_to='input_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])]),
        ),
    ]
